name: null-demo
services:
    database:        
        image: container-registry.oracle.com/database/free:latest
        ports:
            - 1521:1521
        networks:
            - network        
        restart: unless-stopped
        volumes:
            - oracle_data:/opt/oracle/oradata
        environment:
            ORACLE_PWD: ${ORACLE_PWD}
            ORACLE_PDB: ${ORACLE_PDB}
volumes:    
    oracle_data:    
networks:
    network: